* NOTICE

*As of July 2023, [[https://github.com/leathekd/erc-hl-nicks/issues/15][erc-hl-nicks is now a part of ERC]]*!

It won't be released bundled with Emacs until version 30.1 but is already in ERC
available on the Emacs [[https://elpa.gnu.org/packages/erc.html][GNU ELPA]] repository.

This repo should be considered depricated and will be archived once 
the next version of ERC is released with Emacs but will be kept "live" 
for now so the Melpa package isn't accidentally removed before the 
new version is released.

- [[https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/ERC-NEWS?id=9bdc5c62#n33][ERC news]]
- [[https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/erc/erc-nicks.el?id=9bdc5c62][New implementation]]

Please don't report issues here for the new version and instead follow the instructions at
[[https://www.gnu.org/software/emacs/manual/html_node/erc/Getting-Help-and-Reporting-Bugs.html][Getting Help and Reporting Bugs]]
in the ERC manual.



* erc-hl-nicks - ERC Module to Highlight Nicknames

** I already have a nickname highlighter, why should I switch?
If you're happy with what you're using, you shouldn't.  (If it ain't
broke...)  BUT, if you are interested in trying something new, here
are some things you should know:
- erc-hl-nicks is based on erc-highlight-nicknames, so it will auto
  colorize nicknames (you don't have to specify colors)
- erc-hl-nicks will ignore certain characters that IRC clients add to
  nicknames to avoid duplicates (nickname, nickname', nickname'',
  etc.)
- erc-hl-nicks can attempt to produce colors with a sufficient amount
  of contrast between the nick color and the background color.

** Installation
*** Via Package (recommended)
Pick your favorite package archive- I do try to keep this package
up-to-date on Marmalade and it is also available via Mepla and
Melpa-stable.

#+BEGIN_EXAMPLE
(require 'package)

(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)

;; Either of these will work, as well.

;; (add-to-list 'package-archives
;;              '("marmalade" . "http://marmalade-repo.org/packages/") t)

;; (add-to-list 'package-archives
;;              '("melpa-stable" . "http://stable.melpa.org/packages/") t)

(package-initialize)
#+END_EXAMPLE

Then you can install it:

#+BEGIN_EXAMPLE
M-x package-refresh-contents
M-x package-install RET erc-hl-nicks RET
#+END_EXAMPLE

*** Manually (via git)
Download the source or clone the repo and add the following 
to ~/.emacs.d/init.el:

#+BEGIN_EXAMPLE
(add-to-list 'load-path "path/to/erc-hl-nicks")
(require 'erc-hl-nicks)
#+END_EXAMPLE
